---
title: "Tidyr: Reshape"
author: "Paloma"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    theme: united
---
```{r setup, include = FALSE}
library(dplyr)
library(tidyverse)
set.seed(2020)
survey <-
  tibble(
    student = rep(c(1:3),3),
    food = c(rep("fruit",3),rep("vegetable",3), rep("icecream",3)),
    rate = abs(round(rnorm(9, mean = 4, sd = 3), 0))) %>% 
  dplyr::arrange(student)

library(kableExtra)
mytable <- function(df){
  kable(df) %>%
  kable_styling(bootstrap_options = c("hover", "condensed", "responsive"),
                full_width = F,
                font_size = 14)}
```

### Open library

```{r}
library(tidyr)
```

### Tibbles to use
```{r}
table1
table4a
table2
```

### From wide to long

```{r}
cases <- table4a %>% 
  pivot_longer(
    cols = -1,
    names_to = "year",
    values_to = "cases"
  )

cases
```

### From long to wide

```{r}
cases_pop <- table2 %>% 
  pivot_wider(
    names_from = type,
    values_from = count)

cases_pop
```

### Reshaping

```{r}
cases %>% 
  pivot_wider(
    names_from = year,
    values_from = cases
  )

```

```{r}
cases_pop %>% 
  pivot_longer(
    cols = c(3:4),
    names_to = "type",
    values_to = "count"
  )
```

### Formative assessment{.tabset}

#### Exercise

```{r, eval = FALSE, error=TRUE}
survey %>% 
  pivot_____(names_from = "____",
              values_from = "____")
```

We need to transform Table 1, to look as Table 2. Fill in the blanks, correct if necessary:

<div class = "row">
<div class = "col-md-6">

**Table 1**
```{r, echo = FALSE}
survey %>% 
mytable()
```
</div>

<div class = "col-md-6">

**Table 2**

```{r, echo = FALSE}
survey %>%
  pivot_wider(names_from = food,
              values_from = rate) %>% 
  mytable()
```

</div>
</div>

**_To get the dataset run the following code_**

```{r, eval = FALSE}
library(dplyr)

set.seed(2020)

survey <-
  tibble(
    student = rep(c(1:3),3),
    food = c(rep("fruit",3),rep("vegetable",3), rep("icecream",3)),
    rate = abs(round(rnorm(9, mean = 4, sd = 3), 0))) %>% 
  arrange(student)

survey
```

#### Solution

```{r}
survey %>%
  pivot_wider(names_from = food,
              values_from = rate)
```

